<section class="mbr-section mbr-section--relative mbr-section--fixed-size" id="social-buttons2-5" style="background-color: rgb(240, 240, 240);">
    <div class="mbr-section__container container">
        <div class="mbr-header mbr-header--inline row" style="padding-top: 40.8px; padding-bottom: 40.8px;">
            <div class="col-sm-4">
                <h3 class="mbr-header__text">SÍGUENOS</h3>
            </div>
            <div class="mbr-social-icons mbr-social-icons--style-1 col-sm-8">
							<a class="mbr-social-icons__icon socicon-bg-facebook" title="Facebook" target="_blank"><i class="socicon socicon-facebook"></i></a>
						 	<a class="mbr-social-icons__icon socicon-bg-googleplus" title="Google+" target="_blank"><i class="socicon socicon-googleplus"></i></a>
					 </div>
        </div>
    </div>
</section>
<script  src="views/js/jquery.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="views/js/bootstrap.min.js"></script>
</body>
